spring.application.name=Nordholm
spring.datasource.url=jdbc:postgresql://db.dfjsszmwjlbkhlyqpxzo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=#pr%a,3J@A7#dsr

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect